ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "gdpr_consent" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "whatsapp_consent" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "email_consent" BOOLEAN NOT NULL DEFAULT false;
